<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<center><h1>Inquisición Medieval</h1></center>
            <center><img src="<?php echo base_url(); ?>/public/IMG/IMG5.jpg" width="350" height="250"></center>
            <p>Aunque el procedimiento inquisitorial como medio para combatir la herejía es una práctica antigua de la Iglesia católica, la Inquisición episcopal, primera fórmula de la Inquisición medieval, fue establecida en 1184 mediante la bula del papa Lucio III Ad abolendam, como un instrumento para acabar con la herejía cátara. El castigo físico a los herejes había sido dispuesto con anterioridad por Federico II Hohenstaufen, la institución de la Inquisición se dio para detener los abusos que estos procesos podrían sufrir por parte del poder civil. Mediante esta bula, se exigía a los obispos que interviniesen activamente para extirpar la herejía y se les otorgaba la potestad de juzgar y condenar a los herejes de su diócesis.</p>
            <p>En las siguientes décadas, el proceso de la Inquisición resultó intermitente y contradictorio en muchas ocasiones. Un ejemplo fue el caso del primer director de la Inquisición de Hungría, Paulus Hungarus, quien defendió a los chamanes paganos húngaros valiéndose de su influencia con el papa Inocencio III. Además, aseguró que estos al adorar al sol adoraban al ente supremo que era el mismo Dios, así que no hallaba razón para condenarlos. Paulus Hungarus fue uno de los primeros frailes dominicos, quien escribió importantes documentos como la Suma de poenitentiae, tendiendo las bases de la nueva orden a petición de Domingo de Guzmán. Sin embargo, Paulus fue destituido y reemplazado por un religioso más estricto cerca de 1232, después de haberse iniciado propiamente la Inquisición.</p>
            <center><img src="<?php echo base_url(); ?>/public/IMG/IMG6.jpg" width="350" height="250"></center>
            <p>En 1231, ante el fracaso de la Inquisición episcopal, denominada así porque no dependía de una autoridad central, sino que era administrada por los obispos locales, Gregorio IX creó mediante la bula Excommunicamus la Inquisición pontificia o Inquisición papal, dirigida directamente por el papa y dominada por las órdenes mendicantes, especialmente los dominicos. El hecho de que religiosos bajo el control directo del Papa tuvieran a su cargo los tribunales, fue un freno a su expansión, ya que algunos obispos no querían ver limitado su poder en una diócesis por la presencia de estos organismos papales.</p>
            <p>En 1252, el papa Inocencio IV autorizó en la bula Ad extirpanda el uso de la tortura para obtener la confesión de los reos. Se recomendaba a los torturadores no se excedieran hasta el punto de mutilar al reo o finiquitarlos. Las penas eran variables. Los que se negaban a abjurar, "herejes relapsos", eran entregados al brazo secular para la ejecución de la pena de muerte.</p>
            <p>La Inquisición pontificia funcionó sobre todo en el sur de Francia y en el norte de Italia. En España, existió en la Corona de Aragón desde 1249, pero no en la de Castilla.</p>
		</div>	
	</div>
</div>