<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<center><h1>Inquisición Española</h1></center>
            <center><img src="<?php echo base_url(); ?>/public/IMG/IMG7.jpg" width="350" height="250"></center>
            <p>La Inquisición real se implantó en la Corona de Castilla en 1478 por la bula del papa Sixto IV Exigit sincerae devotionis con la finalidad de combatir las prácticas judaizantes de los judeoconversos de Sevilla, uno de cuyos condenados se llamaba: 'Yusif Franco', caso del que más tarde vieron irregularidades procesales. A diferencia de la Inquisición medieval, la impulsó directamente la monarquía, es decir, los Reyes Católicos. Tras una nueva bula emitida en 1483, la Inquisición se extendió a los reinos de la Corona de Aragón, incluyendo Sicilia y Cerdeña, y a los territorios de América (hubo tribunales de la Inquisición en México, Lima y Cartagena de Indias), y se nombró Inquisidor General a Tomás de Torquemada, de familia de conversos, el confesor de Isabel, Espina, había sido rabino. La Inquisición se convirtió en la única institución común a todos los españoles, con excepción de la propia Corona, a quien servía como instrumento del poder real: era un organismo policial interestatal, capaz de actuar a ambos lados de las fronteras entre las coronas de Castilla y Aragón, mientras que los agentes ordinarios de la Corona no podían rebasar los límites jurisdiccionales de sus respectivos reinos.</p>
            <center><img src="<?php echo base_url(); ?>/public/IMG/IMG8.jpg" width="350" height="250"></center>
            <center><h2>Procedimento Judicial</h2></center>
            <p>Al establecerse el <b>Tribunal del Santo Oficio</b>, los primeros procedimientos consistían en una ceremonia llamada el "Juramento", en la que, como lo dice el nombre, los asistentes juraban denunciar a todas las personas que consideraran sospechosas y prestar al tribunal la ayuda que pudiesen, pero, además, al concluir esa ceremonia se solía dar lectura a un edicto de los inquisidores, llamado edicto de gracia, por el cual se conminaba a quienes se sintieran culpables a denunciarse a sí mismos dentro de un plazo fijado; a cambio, obtenían por lo general el perdón de la pena de muerte o la prisión perpetua, así como el de la pena de confiscación de bienes. En el edicto se indicaban con minuciosidad los hechos considerados punibles, aunque su objetivo final era lograr de los autoinculpados la identificación de sus cómplices; es decir, el edicto de gracia en era en realidad un mecanismo para provocar denuncias, convirtiéndose en una trampa que permitía a los inquisidores la formación de un fichero preliminar de sospechosos. En el edicto general de gracia de 1815 se dio potestad a los propios confesores para practicar y recibir testimonios de herejía, prohibiendo a los confesores dar la absolución a los que de algún modo no hubieren cumplido con aquel mandamiento. Más adelante, el juramento primigenio de delación también adquirió la forma escrita, siendo leído por el cura a los feligreses una vez al año; esta figura tomó el nombre de edicto de fe, leyéndose una semana después el edicto de anatema, que declaraba excomulgado a quien no hubiera denunciado lo que sabía acerca de sus vecinos.</p>
            <p>Toda denuncia, incluso anónima, era válida. Una vez recibida, se abría de inmediato una investigación secreta que al revelar algún indicio, por débil que fuera, conducía al apoderamiento de la persona indiciada y al aseguramiento de sus bienes. Se le tomaba enseguida una declaración que incluía siempre preguntas sobre su familia y su origen, sobre su conocimiento de los dogmas y prácticas sobre la religión católica, y sobre si tenía alguna sospecha acerca del motivo de su prisión. Por lo general el acusado manifestaba total ignorancia a ese respecto, temeroso de implicarse en algún hecho que no figurara en la denuncia, situación que agravaba su caso. Si después de preguntarle tres veces el acusado persistía en la misma respuesta se le declaraba "negativo" y se abría propiamente hablando el proceso. Durante toda la secuela de este —que a veces tardaba años— el acusado permanecía incomunicado en la llamada cárcel del secreto y ni siquiera podía hablar con él uno de los inquisidores si faltaba alguien que pudiera servir de testigo. El acusado nunca era informado del nombre de quienes declaraban en el proceso, no había por supuesto la posibilidad de careos y el recurso de tachar a un testigo por ser enemigo del acusado solo podía hacerse efectivo si este adivinaba quien había declarado en su contra o por torpeza del acusado en las declaraciones del testigo. A todos los testigos se les exigía el juramento del secreto.</p>
            <p>Como medio para obtener las confesiones era habitual el uso del tormento. La sentencia ponía fin al proceso, y podía consistir en la absolución del reo (hecho infrecuente) o en su condena. En este último caso, se procedía a la lectura pública de los veredictos en presencia de los acusados y concurriendo las grandes autoridades, constituyendo un aparato ceremonial llamado auto de fe; en este mismo acto se entregaba al verdugo a los condenados a muerte, pena máxima consistente en la ejecución en la hoguera. Otras penas podían consistir en azotes, destierro, confiscación de bienes, galeras, sambenito o reclusión, en cuyo caso se cumplía el confinamiento en las llamadas casas de penitencia.</p>
            <center><img src="<?php echo base_url(); ?>/public/IMG/IMG9.jpg" width="350" height="250"></center>
            <p></p>
		</div>	
	</div>
</div>